language: node_js
node_js:
<<<<<<< HEAD
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
=======
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  
notifications:
  email:
    - k2r79@hotmail.fr
    - mailys.airouche@gmail.com
    - vermerschth@gmail.com
    - souan.edouard0@gmail.com
  on_success: change
  on_failure: always
>>>>>>> 2ada6a16ad1afcbadbc4d1be850c7bb729eeb42e
