language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  
before_script:
  - npm install -g grunt-cli
  
notifications:
  email:
    - k2r79@hotmail.fr
    - mailys.airouche@gmail.com
    - vermerschth@gmail.com
    - souan.edouard0@gmail.com
  on_success: change
  on_failure: always
